using System.Reflection;
using SPTarkov.DI.Annotations;
using SPTarkov.Server.Core.DI;
using SPTarkov.Server.Core.Extensions;
using SPTarkov.Server.Core.Helpers;
using SPTarkov.Server.Core.Models.Common;
using SPTarkov.Server.Core.Models.Eft.Common.Tables;
using SPTarkov.Server.Core.Models.Enums;
using SPTarkov.Server.Core.Models.Spt.Mod;
using SPTarkov.Server.Core.Models.Utils;
using SPTarkov.Server.Core.Services;
using SPTarkov.Server.Core.Utils;

namespace DewarsTweaks;

/// <summary>
/// Runs after Fence assorts are generated (TraderCallbacks = 800000). The stock generator's
/// per-category ItemTypeLimits is a no-op in this SPT version (AddItemAssorts increments a
/// value-type COPY of the limit tuple, never the dictionary), so item counts come out random
/// and weighted by pool size - barter categories with huge pools dominate. So instead of
/// re-pricing the generator's bad output, we REBUILD both Fence assorts from the base fence
/// assort pool, picking EXACTLY the configured count per category, pricing each from the live
/// flea price * multiplier (per-category or global), and setting each item's "durability"
/// (key uses / weapon-armor durability / med resource) from config. Phase A freezes the assort
/// so these replacements stick for the whole session.
/// </summary>
[Injectable(TypePriority = OnLoadOrder.TraderCallbacks + 1)]
public class DewarsFencePricing(
    ISptLogger<DewarsFencePricing> logger,
    ModHelper modHelper,
    DatabaseService databaseService,
    RagfairPriceService ragfairPriceService,
    FenceService fenceService,
    RandomUtil randomUtil)
    : IOnLoad
{
    public Task OnLoad()
    {
        var pathToMod = modHelper.GetAbsolutePathToModFolder(Assembly.GetExecutingAssembly());
        var config = modHelper.GetJsonDataFromFile<ModConfig>(pathToMod, "config/config.json");

        if (!config.ReplaceFenceCategories)
            return Task.CompletedTask;

        var counts = config.FenceCategoryCounts;
        if (counts == null || counts.Count == 0)
            return Task.CompletedTask;

        var items = databaseService.GetItems();
        var min = Math.Clamp(Math.Min(config.FenceDurabilityMinPercent, config.FenceDurabilityMaxPercent), 0, 100);
        var max = Math.Clamp(Math.Max(config.FenceDurabilityMinPercent, config.FenceDurabilityMaxPercent), 0, 100);

        var categoryIds = counts.Keys.Select(k => new MongoId(k)).ToHashSet();

        // Base fence assort pool = every non-blacklisted item (one entry each), generated by
        // FenceBaseAssortGenerator and respecting Phase A's blacklist.
        var baseAssort = databaseService.GetTrader(Traders.FENCE)?.Assort;
        if (baseAssort?.Items == null || baseAssort.Items.Count == 0)
        {
            logger.Warning("[Dewar's Tweaks] Base fence assort empty; skipping rebuild.");
            return Task.CompletedTask;
        }

        // Group base-pool root items by which configured category they belong to.
        var byCategory = new Dictionary<string, List<Item>>();
        foreach (var root in baseAssort.Items.Where(IsAssortRoot))
        {
            var cat = FindCategory(root.Template, categoryIds, items);
            if (cat == null) continue;
            (byCategory.TryGetValue(cat, out var list) ? list : byCategory[cat] = []).Add(root);
        }

        var mainAssort = BuildAssort(baseAssort, byCategory, items, config, min, max, 1);
        var discountAssort = BuildAssort(baseAssort, byCategory, items, config, min, max, 2);

        fenceService.SetFenceAssort(mainAssort);
        fenceService.SetFenceDiscountAssort(discountAssort);

        var mainCount = mainAssort.Items.Count(IsAssortRoot);
        var discountCount = discountAssort.Items.Count(IsAssortRoot);
        logger.Success(
            $"[Dewar's Tweaks] Fence rebuilt: {mainCount} main + {discountCount} discount offers, " +
            $"exact per-category counts, flea prices, durability {min}-{max}%.");

        return Task.CompletedTask;
    }

    private static bool IsAssortRoot(Item item) =>
        string.Equals(item.SlotId, "hideout", StringComparison.OrdinalIgnoreCase) && item.Upd?.SptPresetId == null;

    /// <summary>
    /// Build a fresh fence assort: for each configured category pick exactly N root items from
    /// the base pool (random, no repeats), copy each item-with-children with remapped ids, set
    /// flea price and durability.
    /// </summary>
    private TraderAssort BuildAssort(TraderAssort baseAssort, Dictionary<string, List<Item>> byCategory,
        IDictionary<MongoId, TemplateItem> items, ModConfig config, int min, int max, int loyaltyLevel)
    {
        var resultItems = new List<Item>();
        var barterScheme = new Dictionary<MongoId, List<List<BarterScheme>>>();
        var loyalLevelItems = new Dictionary<MongoId, int>();

        foreach (var (cat, count) in config.FenceCategoryCounts)
        {
            if (count <= 0) continue;
            if (!byCategory.TryGetValue(cat, out var pool) || pool.Count == 0) continue;

            var mult = config.FenceCategoryPriceMultipliers.TryGetValue(cat, out var m) ? m : config.FencePriceMultiplier;

            // Random pick without repeats; clamp to available pool size.
            var picks = pool.OrderBy(_ => Guid.NewGuid()).Take(Math.Min(count, pool.Count));

            foreach (var root in picks)
            {
                // Copy root + children with fresh unique ids (avoids id collisions / dupes).
                var subtree = baseAssort.Items.GetItemWithChildren(root.Id).ToList();
                var idMap = subtree.ToDictionary(it => it.Id, _ => new MongoId());

                var newRootId = idMap[root.Id];
                foreach (var src in subtree)
                {
                    var isRoot = src.Id == root.Id;
                    var clone = new Item
                    {
                        Id = idMap[src.Id],
                        Template = src.Template,
                        SlotId = src.SlotId,
                        ParentId = isRoot
                            ? "hideout"
                            : (src.ParentId != null && idMap.TryGetValue(new MongoId(src.ParentId), out var mapped)
                                ? mapped.ToString()
                                : src.ParentId),
                        Upd = isRoot ? BuildRootUpd(src.Template, items, min, max) : src.Upd,
                    };
                    resultItems.Add(clone);
                }

                var price = Math.Max(1, Math.Round(ragfairPriceService.GetFleaPriceForItem(root.Template) * mult));
                barterScheme[newRootId] = [[new BarterScheme { Count = price, Template = Money.ROUBLES }]];
                loyalLevelItems[newRootId] = loyaltyLevel;
            }
        }

        return new TraderAssort
        {
            Items = resultItems,
            BarterScheme = barterScheme,
            LoyalLevelItems = loyalLevelItems,
            NextResupply = baseAssort.NextResupply,
        };
    }

    /// <summary>Build a root item Upd: stack size 1 plus randomised durability for its type.</summary>
    private Upd BuildRootUpd(MongoId template, IDictionary<MongoId, TemplateItem> items, int min, int max)
    {
        var upd = new Upd { StackObjectsCount = 1 };
        if (!items.TryGetValue(template, out var dbItem) || dbItem.Properties == null)
            return upd;

        var pct = (min == max ? min : randomUtil.GetInt(min, max)) / 100.0;
        var props = dbItem.Properties;

        if ((props.MaximumNumberOfUsage ?? 0) > 1)
        {
            // Keys: NumberOfUsages is uses CONSUMED (0 = pristine).
            var maxUses = props.MaximumNumberOfUsage!.Value;
            var consumed = (int)Math.Round(maxUses * (1 - pct));
            upd.Key = new UpdKey { NumberOfUsages = Math.Clamp(consumed, 0, maxUses - 1) };
        }
        else if ((props.MaxDurability ?? 0) > 0)
        {
            var maxDura = props.MaxDurability!.Value;
            upd.Repairable = new UpdRepairable { Durability = Math.Round(maxDura * pct), MaxDurability = maxDura };
        }
        else if ((props.MaxHpResource ?? 0) > 0)
        {
            upd.MedKit = new UpdMedKit { HpResource = Math.Round(props.MaxHpResource!.Value * pct) };
        }
        else if ((props.MaxResource ?? 0) > 0)
        {
            var maxRes = props.MaxResource!.Value;
            var remaining = Math.Round(maxRes * pct);
            upd.Resource = new UpdResource { Value = remaining, UnitsConsumed = maxRes - remaining };
        }

        return upd;
    }

    /// <summary>Walk an item's parent chain to find which configured category id it belongs to.</summary>
    private string? FindCategory(MongoId itemId, HashSet<MongoId> categoryIds, IDictionary<MongoId, TemplateItem> items)
    {
        var cur = itemId;
        for (var i = 0; i < 32; i++)
        {
            if (categoryIds.Contains(cur)) return cur.ToString();
            if (!items.TryGetValue(cur, out var tpl)) break;
            cur = tpl.Parent;
        }
        return null;
    }
}
